# Generated by Django 5.1.4 on 2024-12-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_boxdesign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxdesign',
            name='depth',
            field=models.FloatField(help_text='Depth of the box in cm.'),
        ),
        migrations.AlterField(
            model_name='boxdesign',
            name='height',
            field=models.FloatField(help_text='Height of the box in cm.'),
        ),
        migrations.AlterField(
            model_name='boxdesign',
            name='logo',
            field=models.ImageField(help_text='Logo image for the box design.', upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='boxdesign',
            name='material',
            field=models.CharField(choices=[('Cardboard', 'Cardboard'), ('Plastic', 'Plastic'), ('Metal', 'Metal')], help_text='Material of the box.', max_length=50),
        ),
        migrations.AlterField(
            model_name='boxdesign',
            name='text',
            field=models.TextField(help_text='Text or description on the box.'),
        ),
        migrations.AlterField(
            model_name='boxdesign',
            name='width',
            field=models.FloatField(help_text='Width of the box in cm.'),
        ),
        migrations.AlterField(
            model_name='cdr',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='design',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='design',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='designtynorbox',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='designtynorbox',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
