# Generated by Django 5.1.4 on 2025-01-02 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_boxdesign_depth_alter_boxdesign_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxdesign',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='boxdesign',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='box_designs', to=settings.AUTH_USER_MODEL),
        ),
    ]
